import { clientsClaim } from "workbox-core";
import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from "workbox-strategies";

clientsClaim();

// Precache files generated by Vite build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache static assets (JS, CSS)
registerRoute(
  ({ request }) =>
    request.destination === "script" || request.destination === "style" || request.destination === "document",
  new CacheFirst({
    cacheName: "static-resources",
  })
);

// Cache News API - Network First
registerRoute(
  ({ url }) => url.origin.includes("newsapi.org"),
  new NetworkFirst({
    cacheName: "news-api-cache",
  })
);

// Cache images - Stale while revalidate
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: "image-cache",
  })
);

self.addEventListener("message", (event) => {
  if (!event.data) return;
  if (event.data.type === "CLEAR_CACHE") {
    caches.keys().then(keys => {
      keys.forEach(key => caches.delete(key));
    });
    event.ports[0]?.postMessage({ result: "Cache cleared" });
  }
});

self.skipWaiting();